import { Component } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrl: './home.component.sass',
})
export class HomeComponent {
  projects: any[] = [
    {
      imgproject: 'assets/img-portfolio.png',
      altimgproject: 'Imagem do site',
      titleproject: 'Portfólio',
      imgskills1: 'assets/html.svg',
      altskills1: 'HTML5',
      imgskills2: 'assets/tailwind.png',
      altskills2: 'Tailwind',
      imgskills3: 'assets/angular.svg',
      altskills3: 'Angular',
      imgskills4: 'assets/typescript.svg',
      altskills4: 'TypeScript',
      imgskills5: 'assets/figma.svg',
      altskills5: 'Figma',
    },
    {
      imgproject: 'assets/img-portfolio.png',
      altimgproject: 'Imagem do site',
      titleproject: 'Portfólio 2',
      imgskills1: 'assets/java.svg',
      altskills1: 'HTML5',
      imgskills2: 'assets/tailwind.png',
      altskills2: 'Tailwind',
      imgskills3: 'assets/angular.svg',
      altskills3: 'Angular',
      imgskills4: 'assets/typescript.svg',
      altskills4: 'TypeScript',
      imgskills5: 'assets/figma.svg',
      altskills5: 'Figma',
    },
    {
      imgproject: 'assets/img-portfolio.png',
      altimgproject: 'Imagem do site',
      titleproject: 'Portfólio 3',
      imgskills1: 'assets/javascript.svg',
      altskills1: 'HTML5',
      imgskills2: 'assets/tailwind.png',
      altskills2: 'Tailwind',
      imgskills3: 'assets/angular.svg',
      altskills3: 'Angular',
      imgskills4: 'assets/typescript.svg',
      altskills4: 'TypeScript',
      imgskills5: 'assets/figma.svg',
      altskills5: 'Figma',
    },
    {
      imgproject: 'assets/img-portfolio.png',
      altimgproject: 'Imagem do site',
      titleproject: 'Portfólio',
      imgskills1: 'assets/html.svg',
      altskills1: 'HTML5',
      imgskills2: 'assets/tailwind.png',
      altskills2: 'Tailwind',
      imgskills3: 'assets/angular.svg',
      altskills3: 'Angular',
      imgskills4: 'assets/typescript.svg',
      altskills4: 'TypeScript',
      imgskills5: 'assets/figma.svg',
      altskills5: 'Figma',
    },
    {
      imgproject: 'assets/img-portfolio.png',
      altimgproject: 'Imagem do site',
      titleproject: 'Portfólio',
      imgskills1: 'assets/html.svg',
      altskills1: 'HTML5',
      imgskills2: 'assets/tailwind.png',
      altskills2: 'Tailwind',
      imgskills3: 'assets/angular.svg',
      altskills3: 'Angular',
      imgskills4: 'assets/typescript.svg',
      altskills4: 'TypeScript',
      imgskills5: 'assets/figma.svg',
      altskills5: 'Figma',
    },
    {
      imgproject: 'assets/img-portfolio.png',
      altimgproject: 'Imagem do site',
      titleproject: 'Portfólio',
      imgskills1: 'assets/html.svg',
      altskills1: 'HTML5',
      imgskills2: 'assets/tailwind.png',
      altskills2: 'Tailwind',
      imgskills3: 'assets/angular.svg',
      altskills3: 'Angular',
      imgskills4: 'assets/typescript.svg',
      altskills4: 'TypeScript',
      imgskills5: 'assets/figma.svg',
      altskills5: 'Figma',
    },
    {
      imgproject: 'assets/img-portfolio.png',
      altimgproject: 'Imagem do site',
      titleproject: 'Portfólio',
      imgskills1: 'assets/html.svg',
      altskills1: 'HTML5',
      imgskills2: 'assets/tailwind.png',
      altskills2: 'Tailwind',
      imgskills3: 'assets/angular.svg',
      altskills3: 'Angular',
      imgskills4: 'assets/typescript.svg',
      altskills4: 'TypeScript',
      imgskills5: 'assets/figma.svg',
      altskills5: 'Figma',
    },
    {
      imgproject: 'assets/img-portfolio.png',
      altimgproject: 'Imagem do site',
      titleproject: 'Portfólio',
      imgskills1: 'assets/html.svg',
      altskills1: 'HTML5',
      imgskills2: 'assets/tailwind.png',
      altskills2: 'Tailwind',
      imgskills3: 'assets/angular.svg',
      altskills3: 'Angular',
      imgskills4: 'assets/typescript.svg',
      altskills4: 'TypeScript',
      imgskills5: 'assets/figma.svg',
      altskills5: 'Figma',
    },
    {
      imgproject: 'assets/img-portfolio.png',
      altimgproject: 'Imagem do site',
      titleproject: 'Portfólio',
      imgskills1: 'assets/html.svg',
      altskills1: 'HTML5',
      imgskills2: 'assets/tailwind.png',
      altskills2: 'Tailwind',
      imgskills3: 'assets/angular.svg',
      altskills3: 'Angular',
      imgskills4: 'assets/typescript.svg',
      altskills4: 'TypeScript',
      imgskills5: 'assets/figma.svg',
      altskills5: 'Figma',
    },
  ];
  projectsToShow = 3;

  loadMoreProjects() {
    this.projectsToShow += 3;
  }
}
